version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    env_file: ./frontend/.env
    environment:
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    networks:
      - weather-app
  api-server:
    image: api-server
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    environment:
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
    networks:
      - weather-app
networks:
  weather-app:
    driver: bridge
